include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoteyActivator

NoteyActivator_FILES = $(wildcard *.m)
NoteyActivator_LIBRARIES = activator
NoteyActivator_EXTRA_FRAMEWORKS = Cephei
NoteyActivator_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
